[project]
name = "metrics_proto"
version = "0.1.0"
description = "Generated gRPC Python stubs"
requires-python = ">=3.11"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
